
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: user001
    password: 123456
    url: jdbc:mysql://123.206.84.216:3306/glacier?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
    hibernate:
            ddl-auto: update
server:
  port: 8123

