
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/product_test?characterEncoding=utf-8&userSSL=false

  jpa:
    show-sql: true
    hibernate:
            ddl-auto: update
server:
  servlet:
    context-path: /sell



